### ISSUE TITLE
Improve asm.shortcut

### ISSUE THREAD

**Issue by radare** [radareorg/ideas#217]
The name is probably misleading. i use to think as "hotkey"

The values should be:

* 0 = no shortcut
* 1 = show at the left of the offset
* 2 = show at the right of the offset
* 3 = show at the right of the bytes
* 4 = show at the right of the disasm as a comment

imho the default should be 1 or 2, but changing this can result on lot of XX so we must think wisely

**Comment by trufae** [comment]
I already implemented this
