### ISSUE TITLE
Provide Nix configuration for setting up radare2/Cutter/r2ghidra-dec/r2pipe/bindings development environment.

### ISSUE THREAD

**Issue by XVilka** [radareorg/ideas#246]
[Nix](https://nixos.org/learn.html) is a cross-platform package manager that utilizes a purely functional deployment model where software is installed into unique directories generated through cryptographic hashes. Dependencies from each software installation are included within each hash, solving the problem of dependency hell. This novel approach to package management promises to generate more reliable, reproducible, and portable packages.

Nix packages are defined through a lazy functional programming language specifically designed for package management. Dependencies are tracked directly in this language through special values called "derivations" which are installed by Nix lazily. Nix keeps track of these references automatically so that installed packages can be garbage collected when no other package depends on them. At the cost of greater storage requirements, all upgrades in Nix are guaranteed to be both atomic and capable of efficient roll-back. This also enables multiple users to safely install software on the same system without administrator privileges.

Nix has full support for Linux and macOS and can safely be installed side-by-side with an existing package manager, though some workarounds are required for Catalina.

Nix solves the issue of spending hours (potentially) just to setup an environment. All derivations are installed in the Nix store, a directory containing the result of building a derivation. You can think of a derivation as a recipe for how to build a program or a library. This is will help significantly reduce the barrier for new contributors.

- https://medium.com/better-programming/easily-reproducible-development-environments-with-nix-and-direnv-e8753f456110
- https://nixos.wiki/wiki/Development_environment_with_nix-shell

cc @trufae @ret2libc @thestr4ng3r @wargio @kazarmy @ITAYC0HEN @karliss @xarkes

**Comment by ret2libc** [comment]
IMHO it is not something we should care about... If people want to support nix packages they can create it and we can for sure help/support them, but it is not something we should do ourselves. We have other more important things to do than to create ourselves all the various package formats that exist. Let's leave this job to package maintainers.

**Comment by XVilka** [comment]
It's not merely a package - I recommend to read what Nix exactly is.

**Comment by ret2libc** [comment]
Still, it is mainly a package... I'm just saying that IMO this should take no priority what's so ever on other kind of issues/ideas. If you want to work on it personally and provide PR, as usual, nobody prevents somebody to do that, but I don't think this should be in any kind of milestone, blocker, roadmap or anything. It is just a maybe-nice-to-have-for-small%-of-people thing. I don't think IDA or others are chosen because they have nix packages.

**Comment by XVilka** [comment]
I am talking about **reproducible development and build environment**. You do just run "nix-shell" and get inside the development environment where radare2, Cutter, etc can be built without a hassle, some development tools probably too. And it's not a container.

**Comment by Pamplemousse** [comment]
@XVilka Yeah, `Nix` is great. Although, development and maintenance of nix expressions is a non trivial task (and not at the core of what ~most~ some OSS projects aim to provide).

That said, I was interested too by seeing radare2 plugins in `nixpkgs`; I started a discussion here: https://discourse.nixos.org/t/radare2-plugins-in-nixpkgs/8485 .
