### ISSUE TITLE
feature-request: r_io_desc_lock

### ISSUE THREAD

**Issue by condret** [radareorg/ideas#256]
If someone wants to do some future-work, pls review thread-api and implement r_io_desc_lock and r_io_desc_unlock. This does not affect progress of siol-merge, but it would motivate me to see it thread-ready

**Comment by trufae** [comment]
I think designing for threadsafe internals requires a much broader view, not ijust in RIO, i'm closing this not because it shouldnt be needed, but because it will require a much extense discussion
