### ISSUE TITLE
Work properly when SDB database are not found

### ISSUE THREAD

**Issue by ret2libc** [radareorg/ideas#268]
According to https://github.com/radareorg/radare2/pull/17192#issuecomment-655482104 there are a lot of `+WARNING: r_anal_cc_arg: assertion 'anal && convention' failed (line 103)` and r2 should work even when SDB database containing those convention are not found.

Probably the user needs a warning message anyway, but maybe just one warning instead of N r_return_if_fail (which essentially are asserts).

**Comment by trufae** [comment]
already fixed
