### ISSUE TITLE
Buffer the whole IO

### ISSUE THREAD

**Issue by radare** [radareorg/ideas#308]
The idea of this is to make RIO work with only RBuffers, this is, reading all the maps and sections

Notes:
* this must be implemented in the siol branch
* unicorn plugin can active this mode, or the user shuold.. in order to map all the buffers in unicorn and r2 at the same time. the buffers cant be reallocated while unicorn is active.

cc @condret

**Comment by trufae** [comment]
There's oom to reopen in malloc, and rbuffer supports io as backend (without caching), but siol have 2 different caching strategies so i think it's fine to close this. @condret reopen if you find it necessary
