### ISSUE TITLE
Replacing ZIP and LZ4 code embeddings with libarchive

### ISSUE THREAD

**Issue by XVilka** [radareorg/ideas#336]
What about dropping ZIP and use [libarchive](https://github.com/libarchive/libarchive) instead? With this we will get all imaginable archive formats for free, it's pure C, compact enough, and allows both compression and decompression. It's actively maintained and regularly checked for the security.

The size of the compiled library in my Fedora 32 x86_64 is **841kb**.

Libarchive will allow us to replace:
- `shlr/zip`
- `shlr/lz4`
- `cabextract` called from `pdb_downloader.c`
- `libr/fs/cpio` plus the corresponding GRUB code.

## Supported Formats

Currently, the library automatically detects and reads the following formats:
  * Old V7 tar archives
  * POSIX ustar
  * GNU tar format (including GNU long filenames, long link names, and sparse files)
  * Solaris 9 extended tar format (including ACLs)
  * POSIX pax interchange format
  * POSIX octet-oriented cpio
  * SVR4 ASCII cpio
  * Binary cpio (big-endian or little-endian)
  * ISO9660 CD-ROM images (with optional Rockridge or Joliet extensions)
  * ZIP archives (with uncompressed or "deflate" compressed entries, including support for encrypted Zip archives)
  * ZIPX archives (with support for bzip2, ppmd8, lzma and xz compressed entries)
  * GNU and BSD 'ar' archives
  * 'mtree' format
  * 7-Zip archives
  * Microsoft CAB format
  * LHA and LZH archives
  * RAR and RAR 5.0 archives (with some limitations due to RAR's proprietary status)
  * XAR archives

The library also detects and handles any of the following before evaluating the archive:
  * uuencoded files
  * files with RPM wrapper
  * gzip compression
  * bzip2 compression
  * compress/LZW compression
  * lzma, lzip, and xz compression
  * lz4 compression
  * lzop compression
  * zstandard compression

The library can create archives in any of the following formats:
  * POSIX ustar
  * POSIX pax interchange format
  * "restricted" pax format, which will create ustar archives except for
    entries that require pax extensions (for long filenames, ACLs, etc).
  * Old GNU tar format
  * Old V7 tar format
  * POSIX octet-oriented cpio
  * SVR4 "newc" cpio
  * shar archives
  * ZIP archives (with uncompressed or "deflate" compressed entries)
  * GNU and BSD 'ar' archives
  * 'mtree' format
  * ISO9660 format
  * 7-Zip archives
  * XAR archives

When creating archives, the result can be filtered with any of the following:
  * uuencode
  * gzip compression
  * bzip2 compression
  * compress/LZW compression
  * lzma, lzip, and xz compression
  * lz4 compression
  * lzop compression
  * zstandard compression

See https://github.com/libarchive/libarchive/wiki/Examples#A_Universal_Decompressor

```c
int r;
ssize_t size;

struct archive *a = archive_read_new();
archive_read_support_compression_all(a);
archive_read_support_format_raw(a);
r = archive_read_open_filename(a, filename, 16384);
if (r != ARCHIVE_OK) {
  /* ERROR */
}
r = archive_read_next_header(a, &ae);
if (r != ARCHIVE_OK) {
  /* ERROR */
}

for (;;) {
  size = archive_read_data(a, buff, buffsize);
  if (size < 0) {
    /* ERROR */
  }
  if (size == 0)
    break;
  write(1, buff, size);
}

archive_read_free(a));
```

Another option would be just to replace current `shlr/zip` with https://github.com/nmoinvaz/minizip

_Originally posted by @XVilka in https://github.com/radareorg/ideas/issues/188#issuecomment-646559882_

**Comment by thestr4ng3r** [comment]
The following from https://github.com/libarchive/libarchive#notes-about-the-library-design might be an issue for io plugins:
> In-place modification and random access to the contents of an archive are not directly supported. For some formats, this is not an issue: For example, tar.gz archives are not designed for random access. In some other cases, libarchive can re-open an archive and scan it from the beginning quickly enough to provide the needed abilities even without true random access. Of course, some applications do require true random access; those applications should consider alternatives to libarchive.

So it has to be checked in detail if libarchive is suitable for everything where libzip is used at the moment

**Comment by thestr4ng3r** [comment]
Also worth mentioning is that r2db already uses libarchive: https://github.com/thestr4ng3r/r2db/blob/master/src/sdb_archive.c
However this dependency is not necessarily final.

**Comment by ret2libc** [comment]
> The following from https://github.com/libarchive/libarchive#notes-about-the-library-design might be an issue for io plugins:
> 
> > In-place modification and random access to the contents of an archive are not directly supported. For some formats, this is not an issue: For example, tar.gz archives are not designed for random access. In some other cases, libarchive can re-open an archive and scan it from the beginning quickly enough to provide the needed abilities even without true random access. Of course, some applications do require true random access; those applications should consider alternatives to libarchive.
> 
> So it has to be checked in detail if libarchive is suitable for everything where libzip is used at the moment.

I do not believe io_zip really needs true random access. We do use functions like `zip_fopen_index` which immediately open a file at position X, but it is also true that we do iterate over all files anyway, so in some ways we already defeat the benefit (see `r_io_zip_open`, `r_io_zip_alloc_zipfileobj`, `r_io_zip_get_by_file_idx`, etc.). 

With regards to `in-place` modification, I don't think we need that either. We can probably reload the file anyway.
I'm personally in favour of including libarchive into r2 and remove all the various out-dated and half-patched *zip implementations we have. :+1:

**Comment by thestr4ng3r** [comment]
In that case, sounds good to me! libarchive has been quite a good library when I used it.

**Comment by trufae** [comment]
meh
