### ISSUE TITLE
Make a port to Sailfish OS

### ISSUE THREAD

**Issue by XVilka** [radareorg/ideas#339]
Radare2 was ported to Maemo OS long time ago, but that OS is dead now, with many successors and the latest one being [Sailfish OS](https://en.wikipedia.org/wiki/Sailfish_OS). It might be interesting to port radare2 to that platform as well.

- https://sailfishos.org/
- https://sailfishos.org/wiki/SailfishOS
- https://sailfishos.org/wiki/Tutorial_-_Building_packages_manually

**Comment by trufae** [comment]
r2 builds and runs fine in sailfishOS, but the work required to maintain an official build and the amount of users using it doesn't pays off the effort imho.

if the situation changes i would love to, but i dont think that requires a ticket at all.
