### ISSUE TITLE
patch binaries in edit mode like in vim for more vim philosophy

### ISSUE THREAD

**Issue by gogo2464** [radareorg/ideas#345]
## Description

*Please describe what are you missing or wanting to be improved*

I think the r2 philosophy is a vim like philosophy. I suggest to set a way to patch instructions like if it was a text file disassembled instead of a command "wa mov rax, rax;".

*Provide images, ascii-art, test files and anything that may help us understand your request*

**Comment by trufae** [comment]
Just press i to insert or A to assemble. There are many visual ways to assemble instructions. Check the help message of visual by pressing ?

**Comment by gogo2464** [comment]
I may have not checked anough documentation yet.

**Comment by trufae** [comment]
I dont think this is documented anywhere its just how visual mode works
