### ISSUE TITLE
Benchmark and optimise hash, io and search

### ISSUE THREAD

**Issue by radare** [radareorg/ideas#38]
This will be useful when moving to SIOL (the io rewrite), or test different io plugins, and hash implementations. When searching we have a counter that shows the current hit count, address, etc.. but we should enhance this status line with bytes/second processed. we can add a config var to specify which option we want to use for that. (dunno if necessary)

**Comment by trufae** [comment]
This issue is obvious and we are doing optimizations all the time on different areas, no need to have a generic issue for this
